server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
        - id: reactive-service
          uri: lb://reactive-service
          predicates:
            - Path=/reactive/**
          filters:
            - StripPrefix=1
        - id: reactive-multitenant-service
          uri: lb://reactive-multitenant-service
          predicates:
            - Path=/reactive-multitenant/**
          filters:
            - StripPrefix=1
